// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: idl/messages/persisted_index.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A request for latest sequential event index that has been persisted to the
// disk or the outputs. This is only needed for inputs that must maintain their
// position in some persistent data sequence between restarts.
type PersistedIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The interval for checking the persisted index value during the subscription.
	// An update is not sent if the value is unchanged, so it's not guaranteed to receive
	// an update after each interval but rather to receive an update on the changed value
	// in `polling_interval` time at most.
	// When the value is zero the response is sent only once and the stream is closed right after.
	PollingInterval *durationpb.Duration `protobuf:"bytes,1,opt,name=polling_interval,json=pollingInterval,proto3" json:"polling_interval,omitempty"`
}

func (x *PersistedIndexRequest) Reset() {
	*x = PersistedIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_messages_persisted_index_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersistedIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistedIndexRequest) ProtoMessage() {}

func (x *PersistedIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_messages_persisted_index_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistedIndexRequest.ProtoReflect.Descriptor instead.
func (*PersistedIndexRequest) Descriptor() ([]byte, []int) {
	return file_idl_messages_persisted_index_proto_rawDescGZIP(), []int{0}
}

func (x *PersistedIndexRequest) GetPollingInterval() *durationpb.Duration {
	if x != nil {
		return x.PollingInterval
	}
	return nil
}

type PersistedIndexReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The uuid of the shipper process, generated on startup. Clients can use this
	// to detect when the shipper restarts.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The highest sequential index that has been persisted. (See the API
	// README for details on what "persisted" entails.)
	PersistedIndex uint64 `protobuf:"varint,2,opt,name=persisted_index,json=persistedIndex,proto3" json:"persisted_index,omitempty"`
}

func (x *PersistedIndexReply) Reset() {
	*x = PersistedIndexReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_messages_persisted_index_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersistedIndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistedIndexReply) ProtoMessage() {}

func (x *PersistedIndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_idl_messages_persisted_index_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistedIndexReply.ProtoReflect.Descriptor instead.
func (*PersistedIndexReply) Descriptor() ([]byte, []int) {
	return file_idl_messages_persisted_index_proto_rawDescGZIP(), []int{1}
}

func (x *PersistedIndexReply) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PersistedIndexReply) GetPersistedIndex() uint64 {
	if x != nil {
		return x.PersistedIndex
	}
	return 0
}

var File_idl_messages_persisted_index_proto protoreflect.FileDescriptor

var file_idl_messages_persisted_index_proto_rawDesc = []byte{
	0x0a, 0x22, 0x69, 0x64, 0x6c, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x70,
	0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x1e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x15, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65,
	0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x44, 0x0a,
	0x10, 0x70, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0f, 0x70, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x22, 0x52, 0x0a, 0x13, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x64,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x27,
	0x0a, 0x0f, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74,
	0x65, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x6a, 0x61, 0x79, 0x6c, 0x65, 0x65, 0x78, 0x2f, 0x67,
	0x65, 0x6f, 0x72, 0x67, 0x65, 0x76, 0x2d, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_messages_persisted_index_proto_rawDescOnce sync.Once
	file_idl_messages_persisted_index_proto_rawDescData = file_idl_messages_persisted_index_proto_rawDesc
)

func file_idl_messages_persisted_index_proto_rawDescGZIP() []byte {
	file_idl_messages_persisted_index_proto_rawDescOnce.Do(func() {
		file_idl_messages_persisted_index_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_messages_persisted_index_proto_rawDescData)
	})
	return file_idl_messages_persisted_index_proto_rawDescData
}

var file_idl_messages_persisted_index_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_idl_messages_persisted_index_proto_goTypes = []interface{}{
	(*PersistedIndexRequest)(nil), // 0: messages.PersistedIndexRequest
	(*PersistedIndexReply)(nil),   // 1: messages.PersistedIndexReply
	(*durationpb.Duration)(nil),   // 2: google.protobuf.Duration
}
var file_idl_messages_persisted_index_proto_depIdxs = []int32{
	2, // 0: messages.PersistedIndexRequest.polling_interval:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idl_messages_persisted_index_proto_init() }
func file_idl_messages_persisted_index_proto_init() {
	if File_idl_messages_persisted_index_proto != nil {
		return
	}
	file_idl_messages_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_idl_messages_persisted_index_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersistedIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_messages_persisted_index_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersistedIndexReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_messages_persisted_index_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idl_messages_persisted_index_proto_goTypes,
		DependencyIndexes: file_idl_messages_persisted_index_proto_depIdxs,
		MessageInfos:      file_idl_messages_persisted_index_proto_msgTypes,
	}.Build()
	File_idl_messages_persisted_index_proto = out.File
	file_idl_messages_persisted_index_proto_rawDesc = nil
	file_idl_messages_persisted_index_proto_goTypes = nil
	file_idl_messages_persisted_index_proto_depIdxs = nil
}
